server:
  port: 8181
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/techlearn
    username: TrucPham
    password: 12345
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0